/*
* HumboldtJSDOM
* http://humboldtjs.com/
*
* Copyright (c) 2012 Daniël Haveman
* Licensed under the MIT license
* http://humboldtjs.com/license.html
*/
package dom.domobjects
{
	public class HTMLFrameElement extends HTMLElement
	{
		include "../../../shared/OnLoad.as";
		
		// Frame/IFrame Object Properties

		/** Sets or returns the value of the align attribute in an iframe. */
		public function get align():String { return null }
		public function set align(value:String):void {}
		/** Returns the document object generated by a frame/iframe. */
		public function get contentDocument():Document { return null }
		/** Returns the window object generated by a frame/iframe. */
		public function get contentWindow():Window { return null }
		/** Sets or returns the value of the frameborder attribute in a frame/iframe. */
		public function get frameBorder():String { return null }
		public function set frameBorder(value:String):void {}
		/** Sets or returns the value of the longdesc attribute in a frame/iframe. */
		public function get longDesc():String { return null }
		public function set longDesc(value:String):void {}
		/** Sets or returns the value of the marginheight attribute in a frame/iframe. */
		public function get marginHeight():int { return 0 }
		public function set marginHeight(value:int):void {}
		/** Sets or returns the value of the marginwidth attribute in a frame/iframe. */
		public function get marginWidth():int { return 0 }
		public function set marginWidth(value:int):void {}
		/** Sets or returns the value of the noresize attribute in a frame. */
		public function get noResize():Boolean { return false }
		public function set noResize(value:Boolean):void {}
		/** Sets or returns the value of the scrolling attribute in a frame/iframe. Allowed values are "auto", "yes" and "no". */
		public function get scrolling():String { return null }
		public function set scrolling(value:String):void {}
		/** Sets or returns the value of the src attribute in a frame/iframe. */
		public function get src():String { return null }
		public function set src(value:String):void {}
	}
}